-- Este script se ejecuta como SYS en la PDB FREEPDB1
CREATE USER BOOKS_APP IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE TO BOOKS_APP;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO BOOKS_APP;
ALTER USER BOOKS_APP QUOTA UNLIMITED ON USERS;
/